/* Generated By:JavaCC: Do not edit this line. SimpleXmlToJsonConstants.java */
package projet2_compilation;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleXmlToJsonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAG_OPEN = 5;
  /** RegularExpression Id. */
  int TAG_CLOSE = 6;
  /** RegularExpression Id. */
  int TAG_END = 7;
  /** RegularExpression Id. */
  int TEXT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<TEXT>",
  };

}
